# Generated by Django 5.2.6 on 2025-09-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('credentialId', models.CharField(blank=True, max_length=200)),
                ('credentialUrl', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, max_length=100)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('image', models.URLField(blank=True, null=True)),
                ('githubUrl', models.URLField(blank=True, null=True)),
                ('liveUrl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('icon', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
