# Generated by Django 5.2.6 on 2025-09-30 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='from-blue-500 to-cyan-500', max_length=50)),
                ('icon', models.CharField(default='Code', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory'),
        ),
    ]
