# Generated by Django 5.2.6 on 2025-09-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skillcategory_remove_skill_icon_alter_skill_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='credentialId',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
