# Generated by Django 5.2.6 on 2025-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_certificate_credentialid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.JSONField(default=list)),
            ],
        ),
    ]
