# Generated by Django 5.2.6 on 2025-09-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Resume', max_length=100),
        ),
    ]
