# Generated by Django 5.2.6 on 2025-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('Higher Education', 'Higher Education'), ('Secondary Education', 'Secondary Education'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='year',
        ),
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.CharField(default='2025', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
