# Generated by Django 5.2.6 on 2025-09-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_education_remove_certificate_year_certificate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='type',
            field=models.CharField(choices=[('Higher Education', 'Higher Education'), ('Secondary Education', 'Secondary Education'), ('Courses', 'Courses'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
