# Generated by Django 5.2.6 on 2025-10-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_education_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='color',
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='color_dark',
            field=models.CharField(default='from-purple-400 to-pink-500', help_text='Tailwind gradient for dark mode (e.g., from-purple-400 to-pink-500)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='color_light',
            field=models.CharField(default='from-purple-400 to-pink-500', help_text='Tailwind gradient for light mode (e.g., from-purple-600 to-pink-600)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='icon',
            field=models.CharField(help_text='Icon name (e.g., Wrench, Database, etc.)', max_length=50),
        ),
    ]
