# Generated by Django 5.2.6 on 2025-10-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_skillcategory_color_skillcategory_color_dark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='color_dark',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='color_light',
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='color',
            field=models.CharField(default='from-blue-500 to-cyan-500', max_length=50),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='icon',
            field=models.CharField(default='Code', max_length=50),
        ),
    ]
