# Generated by Django 5.2.6 on 2025-10-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_skillcategory_color_dark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='color',
        ),
        migrations.AddField(
            model_name='resume',
            name='public_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
