# Generated by Django 5.2.6 on 2025-10-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_skillcategory_color_resume_public_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='public_url',
        ),
    ]
